from enum import Enum


class TemplateType(Enum):
    API_TEMPLATE = 'API_TEMPLATE'
    PROMPT = 'PROMPT'
    #SYSTEM_TEMPLATE = 'SYSTEM_TEMPLATE'
    #AGENT_TEMPLATE = 'AGENT_TEMPLATE'
    #SYNTHESIS_PROMPT = 'SYNTHESIS_PROMPT'
    #CLASSIFIER_TEMPLATE = 'CLASSIFIER_TEMPLATE'

class TemplateName(Enum):
    AGENT_PROMPT = 'CUBEASSIST_PIPELINE_AGENT_AGENT_PROMPT'
    AGENT_SYSTEM_PROMPT = 'CUBEASSIST_PIPELINE_AGENT_SYSTEM_PROMPT'
    AGENT_SYNTHESIS_PROMPT = 'CUBEASSIST_PIPELINE_AGENT_SYNTHESIS_PROMPT'
    AGENT_SKILLS_CLASSIFIER_PROMPT = 'CUBEASSIST_PIPELINE_AGENT_SKILLS_CLASSIFIER_PROMPT'
    VEHICLE_LISTING_API = 'VEHICLE_LISTING_API'
    VEHICLE_LISTING_API_FILTER = 'VEHICLE_LISTING_API_FILTER'
    GET_BOOKMARKS = 'GET_BOOKMARKS'
    CREATE_BOOKMARK = 'CREATE_BOOKMARK'
    UPSERT_BOOKMARK = 'UPSERT_BOOKMARK'
    DELETE_BOOKMARK = 'DELETE_BOOKMARK'
    RENAME_BOOKMARK = 'RENAME_BOOKMARK'
    ADD_VEHICLES_TO_BOOKMARK = 'ADD_VEHICLES_TO_BOOKMARK'
    REMOVE_VEHICLES_FROM_BOOKMARK = 'REMOVE_VEHICLES_FROM_BOOKMARK'
    



